version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:latest # jekyll/builder:latest
    ports:
      - 8888:8888
      - 35729:35729
    environment:
      - http_proxy=
      - https_proxy=
      - HTTP_PROXY=
      - HTTPS_PROXY=
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    command: >
      bash -c "bundle install && bundle exec jekyll serve
      --watch --port=8888 --host=0.0.0.0
      --livereload --verbose --trace --force_polling"

volumes:
  bundle_cache:
